---
title: "Group 27 Project"
author: "Jade Butler, Sonia Saxon, Joanna Mendelsohn, Kai Smith"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE}
library(tidyverse)
library(openintro)
library(rmarkdown)
library(BSDA)
library(infer)
library (ggpubr)
library(car)
library(ggplot2)
library(broom)
```

### Problem 1: Read in and Prepare Data
```{r PR}
Fish <- read.csv("fish.csv")
Fish$Site <- factor(Fish$Site)
Fish$AgeP<- factor(Fish$AgeP)
Fish$YrCaught <- factor(Fish$YrCaught)
Fish$YrTagged <- factor(Fish$YrTagged)
count(Fish) #5345 total observations
Fish2 <- filter(Fish, is.na(YrTagged) | YrCaught == YrTagged) #this is our new data set for the rest of the assignment
count(Fish2) #5306 total observations after filtering out YrCaught > YrTagged
summary(Fish2) #1321 NAs in YrTagged and 2771 NAs in Weight

```



### Problem 3:  EDA
#### Part 3a)
```{r Univariate EDA}
#graph for Age, Weight and Length each
h1 <- ggplot(Fish2, aes(x = AgeP)) +
  geom_bar(fill = "cornflowerblue") + 
  labs(x = "Probable Age", 
       title = "Fish Measured Age 0-3") 
summary(Fish2$AgeP)
h2 <- ggplot(data = Fish2, aes(x = Length)) + 
  geom_histogram(binwidth = 2, 
                 fill = "cornflowerblue") + 
  labs(title = "Captured Fish Measured Length", 
       x = "Length in mm") 
summary(Fish2$Length)
h3 <- ggplot(data = Fish2, aes(x = Weight)) +
  geom_histogram(binwidth = 2, 
                 fill = "cornflowerblue") + 
  labs(title = "Captured Fish Measured Weight", 
       x = "Weight in grams") 
summary(Fish2$Weight)
ggarrange(h1, h2, h3)

```

#### Part 3b)
```{r Bivariate EDA}
#graph for relationship between weight and length
s1 <- scatterplot(Fish2$Length, Fish2$Weight, 
            pch = 19,                  
            col = "cornflowerblue",                    
            smooth = FALSE,             
            regLine = FALSE,
            xlab = "Length in mm", ylab = "Weight in grams",
            cex.axis = 1.2, cex.lab = 1.2, cex = 1.2)
s1
summary(Fish2$Length, Fish2$Weight)
```

### Problem 4:  Regression of Weight on Length
#### Part 4a)
```{r Scatterplot}
s2 <- ggplot(Fish2, aes(x=log(Length), y=log(Weight))) +
  geom_point(color="cornflowerblue", 
             size = 1, 
             alpha=.5) +  
  labs(title = "Natural Log Measured Weight on Measured Length", 
       x = "Natural Log Length in mm", 
       y = "Natural Log Weight in grams")
s2

```



#### Part 4b) weight (y) lenght (x)
```{r Reg W on L}
s3 <- ggplot(Fish2, aes(x=log(Length), y=log(Weight))) +
  geom_point(color="cornflowerblue", 
             size = 1, 
             alpha=.5) +  
  geom_smooth(method = "lm", se = FALSE, color="black") + 
  labs(title = "Natural Log Measured Weight on Measured Length", 
       x = "Natural Log Length in mm", 
       y = "Natural Log Weight in grams")
s3
lm1.out <- lm(log(Fish2$Weight) ~ log(Fish2$Length))
  summary(lm1.out)
```
#### Write out the regression equation and interpret the estimated slope parameter in the context of the problem.
 y = mx + b
### regression equation
intercept = -11.412
slope = 2.99

y = 2.99x - 11.412


#### Part 4c)
```{r Reg Diagnostics}

plot(fitted(lm1.out), residuals(lm1.out),
     xlab="Fitted Values", ylab="Residuals")
abline(h=0)
hist(residuals(lm1.out), xlab="Residuals", main="")
qqnorm(residuals(lm1.out))
qqline(residuals(lm1.out))
```


#### Part 4e)
```{r C.I }
t.test(Fish2$Weight,Fish2$Length, conf.level=0.95)

```


#### Part 4f)
```{r CI and PI}

```


### Problem 5:  Fish Length and Site
#### Part 5a)
```{r FL by Site}
# boxplots of fish length by site

b1 <- ggplot(Fish2, aes(x = Site, y = Length)) + 
  geom_boxplot() + xlab("Site Location") +
  ylab("Fish Fork Length (mm)")
b1
```

#### Part 5b)
```{r Inference for Length}
# two subsets, one for Site 1 data and other for Site 3 data

site1 <- Fish2 %>%
  filter(Site == "Site 1")

site3 <- Fish2 %>%
  filter(Site == "Site 3")

# reporting 95% confidence interval for difference in mean lengths b/w upstream
# and downstream sites

t.test(site1$Length, site3$Length, conf.level = 0.95)$conf.int
```


#### Part 5c)
```{r Testing Claim w/ Signif. Level}
summary(site1)
sd(site1$Length)
nrow(site1)

summary(site3)
sd(site3$Length)
nrow(site3)

tsum.test(87.75, 29.37401, 1418, 78.59, 24.01731, 2222)
```